name: Build Profanity2 (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git ocl-icd-opencl-dev opencl-headers

      - name: Build project
        run: make -j$(nproc)

      - name: Verify binary
        run: ./profanity2 --help

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: profanity2-linux
          path: profanity2
