name: Build Profanity2 (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git ocl-icd-opencl-dev opencl-headers

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --config Release -- -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: profanity2-linux
          path: build/profanity2*
