name: Build Profanity2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git ocl-icd-opencl-dev opencl-headers

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake

      - name: Configure CMake
        run: |
          cmake -S . -B build

      - name: Build project
        run: |
          cmake --build build --config Release -- -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: profanity2-${{ matrix.os }}
          path: build/profanity2*
